project:
  type: website
  output-dir: docs

website:
  title: "PSTAT DEI Subcommittee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Pages/Officers.qmd
        text: Officers
      - href: Pages/About.qmd
        text: About
      - href: Pages/Events.qmd
        text: Calendar and Events
      - href: Pages/Resources.qmd
        text: Resources
      
  page-footer: "Site Originally Designed by Ethan Marzban using <a href='https://quarto.org/' target='_blank'>Quarto</a>; ©2025"
  favicon: "Images/Logos_Icons/hex.svg"

format:
  html:
    theme: 
      light: [sandstone, dark.scss]
    toc: true

